### ISSUE TITLE
DesignVM - 042 Спроектировать форму управления ТМ

### ISSUE THREAD

**Issue by ViktorKuryshev** [ViktorKuryshev/CRM#56]
+ Кликаем вкладку Ресуры
- [x] ++ Issue #65: Создать вкладку Ресурсы
+ Кликам вкладку ТМ
- [x] ++ Issue #66: Создать вкладку ТМ
+ Выводим список всех ТМ
- [x] ++ Issue #64: Создать панель контейнер для панели управления ТМ и панели списка ТМ(TableView)
- [x] ++ Issue #63: Создать панель общего меню управления ТМ
- [x] ++ Issue #59: Создать панель TableView для отображения всех ТМ
